dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1 # space after - is essential 

compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
      # whenever the compiler sees @chainlink it means we are refering smartcontractkit/chainlink-brownie-contracts@1.1.1.

dotenv: .env
networks:
  default: development # note that brownie sets this by default however we can make it anything we would like 
  goerli:
    eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
    verify: True
  mainnet-fork-dev:
    eth_usd_price_feed: '0xaEA2808407B7319A31A383B6F8B60f04BCa23cE2'
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
  ganache-cli:
    verify: False


wallets:
  from_key: ${PRIVATE_KEY}